### ISSUE TITLE
⚖ Implement dynamic colormaps for station parameters

### ISSUE THREAD

**Issue by jkittner** [vogelino/data-2-resilience#82]
Following up on the last meeting where we discussed associated colormaps and typical parameter ranges we came up with the following suggestion (see an implementation below):

1. For each parameter we derived the 5% and 95% percentile from the Bochum stations. If not available, we made and "expert guess"
2. we extended each parameter definition in `colorScaleUtil.ts` with the above values and in addition with valid ranges that are defined by physical limits or mathematical limits e.g. relative humidity 0 - 100%.
3. a fraction (percent) of how many percent of the expected range (between 5th and 95th percentile) has to be present at all times
4. We then check if the criterion of the fractional range is already fullfilled
5. if not, we check if all values are the same (often that's the case for lighting strikes and precipitation), if so, we extend it to the minimum expected range, both toward minimum and maximum
6. if the values differ, we extend the range to the minimum range by what was missing to reach this previously
7. We do a final check that we did not exceed the valid ranges and if so we reset them to the highest possible value - this is useful if there is an outlier in the network which would skew the entire plot.

The results look promising!

![Image](https://github.com/user-attachments/assets/f90118af-eeb5-4433-886a-6b9bb07610be)

**Implementation**

<details>
<summaray>This would be an example of an implementation</summary>

```ts
type ParamSettings = {
  scheme: string;
  perc_5: number;
  perc_95: number;
  valid_min: number;
  valid_max: number;
  fraction: number;
};

const obj: Record<string, ParamSettings> = {
  air_temperature: {
    scheme: "Spectral_r",
    perc_5: 0,
    perc_95: 24,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.25,
  },
  relative_humidity: {
    scheme: "YlGnBu",
    perc_5: 44,
    perc_95: 100,
    valid_min: 0,
    valid_max: 100,
    fraction: 0.5,
  },
  absolute_humidity: {
    scheme: "YlGnBu",
    perc_5: 3,
    perc_95: 14,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  specific_humidity: {
    scheme: "YlGnBu",
    perc_5: 2,
    perc_95: 10,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  atmospheric_pressure: {
    scheme: "YlGnBu",
    perc_5: 983,
    perc_95: 1016,
    valid_min: 860,
    valid_max: 1055,
    fraction: 0.3,
  },
  atmospheric_pressure_reduced: {
    scheme: "YlGnBu",
    perc_5: 998,
    perc_95: 1031,
    valid_min: 860,
    valid_max: 1055,
    fraction: 0.3,
  },
  dew_point: {
    scheme: "YlGnBu",
    perc_5: -3,
    perc_95: 17,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.3,
  },
  heat_index: {
    scheme: "turbo",
    perc_5: -3,
    perc_95: 25,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.3,
  },
  lightning_average_distance: {
    scheme: "viridis",
    perc_5: 0,
    perc_95: 15,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  lightning_strike_count: {
    scheme: "viridis",
    perc_5: 0,
    perc_95: 30,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  mrt: {
    scheme: "Spectral_r",
    perc_5: -4,
    perc_95: 44,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.3,
  },
  pet: {
    scheme: "turbo",
    perc_5: -5,
    perc_95: 25,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.7,
  },
  precipitation_sum: {
    scheme: "Blues",
    perc_5: 0,
    perc_95: 5,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.1,
  },
  solar_radiation: {
    scheme: "YlOrBr",
    perc_5: 0,
    perc_95: 603,
    valid_min: 0,
    valid_max: 1400,
    fraction: 0.3,
  },
  utci: {
    scheme: "turbo",
    perc_5: -3,
    perc_95: 24,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.7,
  },
  vapor_pressure: {
    scheme: "viridis",
    perc_5: 4,
    perc_95: 16,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  wet_bulb_temperature: {
    scheme: "Spectral_r",
    perc_5: -2,
    perc_95: 16,
    valid_min: -Infinity,
    valid_max: Infinity,
    fraction: 0.3,
  },
  wind_speed: {
    scheme: "viridis",
    perc_5: 0,
    perc_95: 4,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
  maximum_wind_speed: {
    scheme: "viridis",
    perc_5: 0,
    perc_95: 8,
    valid_min: 0,
    valid_max: Infinity,
    fraction: 0.3,
  },
};

function compute_colormap_ranges(
  x: Array<number | null>,
  param_obj: ParamSettings
): [number, number] {
  const x_filtered = x.filter((val) => val !== null) as number[];
  const data_min = Math.min(...x_filtered);
  const data_max = Math.max(...x_filtered);
  const data_range = data_max - data_min;
  const expected_range = param_obj.perc_95 - param_obj.perc_5;
  const minimum_range = Math.abs(expected_range * param_obj.fraction);
  // if the data range is greater than the minimum range, use the original data range
  let vmin = data_min;
  let vmax = data_max;

  // the range is smaller, we need to expand it
  if (data_range < minimum_range) {
    if (data_range === 0) {
      vmin = data_min - minimum_range / 2;
      vmax = data_max + minimum_range / 2;
    } else {
      const val_diff = minimum_range - data_range;
      vmin = data_min - val_diff / 2;
      vmax = data_max + val_diff / 2;
    }
  }
  // double check that this is still within the valid range otherwise cut it off and
  // avoid unrealistic values
  if (vmin < param_obj.perc_5 && isFinite(param_obj.perc_5)) {
    vmin = param_obj.perc_5;
  }
  if (vmax > param_obj.perc_95 && isFinite(param_obj.perc_95)) {
    vmax = param_obj.perc_95;
  }
  return [vmin, vmax];
}

/* example usage */

const air_temp = [
  17.64,
  18.16,
  18.172727272727272,
  18.2,
  17.933333333333334,
  17.583333333333332,
  17.62,
  17.744444444444444,
  17.84,
  17.985714285714284,
  17.755555555555556,
  18.108333333333334,
  17.95,
  18.0,
  17.87142857142857,
  17.785714285714285,
  16.991666666666667,
  17.244444444444444,
  17.93076923076923,
  17.555555555555557,
  null,
  17.9,
  18.380956232038866,
  18.0,
  18.526528711236917,
  18.475,
  18.6491279468986,
  18.65940032043949,
  18.24420920119021,
  16.8786930647745,
  18.8702227817197,
  17.623632410162475,
  19.97912082602175,
  18.34616311894408,
  18.134650186922986,
  18.165673304341187,
  18.324085016227354,
  19.912735942626025,
  20.122230699456654,
  18.9218242160678,
  18.798623636224935,
  null,
  18.710040436408033,
  17.95492256046386,
  18.343678534024136,
  18.928344950997747,
  18.55212659901834,
  18.531421201824024,
  null,
  16.85742046234836,
  18.559324533964077,
  18.29983291371019,
  18.302593694633046,
  17.77427792547734,
  18.497533379110425,
  17.5400661126468,
  18.811033162940884,
  19.11866941329064,
  18.649292050743135,
  18.196481015233633,
  17.784296038896592,
  18.947681391622762,
  18.29651026169226,
  18.154197375448263,
  18.40665522240023,
  18.75413633936065,
  18.8749507896544,
  18.898483761857555,
  19.132697922229823,
  18.99632333867397,
  null,
  18.93099997456829,
  18.64327611200124,
  18.067610437171016,
  18.0641926705832,
  null,
];
console.log(compute_colormap_ranges(air_temp, obj.air_temperature));
```

</details>

**Comment by vogelino** [comment]
@jkittner Thank you very much for your explanation and implementation suggestion. I will try to apply it to our codebase and will let you know here. 🙏

**Comment by vogelino** [comment]
@jkittner I was expecting to get fixed scales from you, not dynamic ones. Having dynamic ranges based on values introduce a whole lot of complexity and usability concerns about how the legend looks like when the data is loading, errored, empty, etc. Also, having the legend change when the selection of unit, time range, stations, etc. makes it hard to compare from one value to another. I would suggest you recalculate the min and max value on your side for the whole dataset (so it is fixed) and then either provide me with the hardcoded values or with an API endpoint. What do you think?

PS: Just to be sure, in your example, the array of values represent all values for the current unit in the current view of all selected stations stations?

**Comment by jkittner** [comment]
Just, brief: we discussed that and will add information in the network snapshot return value of the API call. It would look something like that - the `visualization` key is new:

```json
{
  "data": [
    {
      "air_temperature": 15.32,
      "measured_at": "2025-04-23T11:00:00Z",
      "station_id": "DOBBHS",
      "station_type": "biomet"
    },
    {
      "air_temperature": 15.688888888888888,
      "measured_at": "2025-04-23T11:00:00Z",
      "station_id": "DOBBRS",
      "station_type": "biomet"
    },
    ...
  ],
  "visualization": {
    "air_temperature": {
      "suggested_min": 10,
      "suggested_max": 20
    }
  },
  "version": "0.1.dev219+g17e9b5a",
  "timestamp": 1745406633894
}
```
would that help to populate the legend and colors?

**Comment by jkittner** [comment]
Okay, I implemented this and it should be part of the next deployment I will hopefully make later today or tomorrow. Note that this is opt in so you will have to set `suggest_viz=true` otherwise it will be always `null`. I did it that way since it triggers a 2nd db query and does some calculations so it's a bit expensive.

**Comment by vogelino** [comment]
Hi @jkittner. Thank you for implementing this. I'm sorry I couldn't answer earlier. Your suggestion works, however it does not address the other issues I previously mentioned:
- The scale is dependent of the currently displayed/fetched values, so if it is empty or changes, the scale does too. This has real UX implications. It makes comparing two different configurations unintuitive. Something of the same "red" might mean something different. Or am I wrongly understanding the code?
- My suggestion would be to have a fixed scale, fetched once per unit (or overall), that is based on the whole dataset. These scales would be cached and would load instantly, would be predictable and would work even with empty data.

Do you understand my point and do you agree? I'm sorry if you already took time to implement this solution, but I still favour the above solution both from a UX standpoint and in terms of implementation.

**Comment by jkittner** [comment]
> so if it is empty or changes, the scale does too.

This is intended and necessary - see below

> It makes comparing two different configurations unintuitive

We did see this challenges. However, what led us to this result was asking the question what the main function of the map should be. The most important thing it offers in contrast to all other visualizations is the spatial component, building upon this, it also offers spatial selection and far, far after all of this it may offer temporal **AND** spatial comparison by clicking between timesteps. We thought that the temporal component is covered by the line plots, but the spatial component is completely lost when we try to also squeeze in a temporal component. It currently is like that meaning the only useful information one could get from the map is if it is warm-ish or cold-ish and click on stations - no spatial patterns at all - so value of the network showing spatial patterns is lost.
How would one do long-term comparison with the map if we only offer to go back a single month (which makes sense)?
If one compares locations temporarily, one will always have to use a lineplot. Distinguishing small changes only via the color is imprecise and not quantifiable and finally totally depends on the uniform perception the colormap provides (or does not).

> My suggestion would be to have a fixed scale, fetched once per unit (or overall), that is based on the whole dataset.

There is the issue of seasonality. where values during the summer are completely different that during the winter - and that all the time. So the current state would mean every point is blue in winter and every point is read in summer. Which is not our message.

> would be predictable and would work even with empty data.

But what would be the point of having a color scale for empty data?

>  Something of the same "red" might mean something different. Or am I wrongly understanding the code

Yes, that is partially solved by using the different color maps we already do so it is somewhat intuitive and viridis as the default has no intuitive associative quality, I believe.

But after long thinking and trying it is simply impossible to have both in the map: spatial **and** temporal comparability. And since we have line plots that cover the latter, but nothing that covers the former - spatial patterns should have priority.

P.S. I will do some renaming with the params and let you know once it's online where you can look up the final names.

**Comment by vogelino** [comment]
@jkittner Thank you for the detailed explanation, that really helped clarify the reasoning behind your suggestion! I now understand why prioritizing the spatial aspect on the map makes sense, especially since the line plots already cover the temporal comparisons so well. I’ll try to implement things as you suggested.

Regarding the point about having a color scale for empty data: I see your argument. My initial thought was that a fixed color scale could help visualize the range of possible values, even if there’s no data for a given time step, but I agree that if we follow your suggested strategy, it wouldn’t make sense to show colors when there’s no data to display.

Thanks again for the insights and for planning to update the parameter names—I’ll keep an eye out for those changes!

**Comment by jkittner** [comment]
Great! Sorry for the back-and-forth communication was not clear from my end.

The new API version is now online, see: https://api.data2resilience.de/docs#/stations/get_network_snapshot_v1_network_snapshot_get

**Comment by vogelino** [comment]
@jkittner @alsino I haven't been able to implement this until leaving for Venice. This will need to wait for next week... I had some issues with the display of raster layers while implementing #85 

Have a nice weekend! 👋

**Comment by vogelino** [comment]
@jkittner I can use the snapshot API call for creating a color scale that works for the barchart and the stations when the data viz selected is either daily or hourly. However, the line chart uses the `data` endpoint and therefore does not get the visualization suggestion in the response. I can calculate the vmin and vmax on the frontend side but it would be easier and cleaner if there was the `suggest_viz=true` option on the data call too. 

This also means that when changing between the hourly/daily viz type and the range, The colouring of the stations would also need to be different, as they are now based on the scale of the whole line chart data, not the snapshot call of the last day.

Am I missing something? Thank you for your help on this one!

**Comment by jkittner** [comment]
I have a hard time following tbh. Maybe I am not fully up to date?
I don't see a colorbar at the bar chart? What would the colorbar even be used for?

For the linechart I can see one. But other than for the categorical parameters (that are fixed) this does not make too much sense, no?

> This also means that the scale on the bar charts will be different than on the line chart. The colouring of the stations would also need to be different, as they would now be based on the scale of the whole line chart data, not the snapshot call of the last day.

I don't think that makes sense, since we will, yet again, try to cover temporal and spatial dynamics with colors which will lead to the same issues we try to address with this patch.

**Comment by vogelino** [comment]
@jkittner I'm sorry if I wasn't super clear. There is nothing to see yet. I wasn't showing something. I was asking you to add the ability to pass the `suggest_viz=true` to the data API call, so I can also create a dynamic legend when displaying the line chart. Or how do you want me to do the scale when displaying the line chart?

**Comment by vogelino** [comment]
When displaying bar charts, both on the map and on the tooltips we show colors. How is the legend supposed to be when showing the line chart? Should the scale of the stations on the map should be different that the one of the line chart?

**Comment by vogelino** [comment]
@jkittner it seems to only be a miscommunication from my part that has caused confusion. Maybe we can have a short call about that today? Let me know, I want to make sure we are on the same page. (Send me when you are available with a link per email and I'll meet you there).

**Comment by jkittner** [comment]
I double checked with the others. The request for a colormap beside the plot only applies to UTCI and PET (categorical and continous). The colors should indicate the health risk. The other parameters don't need a colormap.
For the continous values it's tricky to decide how to stretch the colormap or what part to show. Probably statically like the raster -sth to +sth and then crop it to the range the line plot covers (likely again only a single color).

I am hesitant to also add this to the data API endpoint since this would again mean we have to run the db query twice if visualization suggestions are requested. This query is much more expensive since the table is much much bigger (millions of rows).

I would be available for a call only later this afternoon ~4-5 PM CEST.

**Comment by vogelino** [comment]
@jkittner now you got me lost. Hahaha. What do you mean "The other parameters don't need a colormap."

> This query is much more expensive since the table is much much bigger (millions of rows).
Unless you process this on the same reduced amount of data you provide via the API. Processing that on the frontend is not going to be fast. But I'm probably understanding it wrong. 

We need to show on the interface consistent color maps for each indicator across all pages. It needs to work in every situation, for regular indicators as well a UTCI / PET, for heat stress as well as for thermal comfort. There are already many exceptions within the code and things are starting to get confusing. Let's please have a talk about that to make sure we are on the same page. 4CEST would be great. If you can earlier let me know. Thank you!

**Comment by vogelino** [comment]
@alsino as discussed on a call with @jkittner, I implemented the dynamic color maps as follows:
- Using the snapshot API endpoint, I gather the min and max
- I used the color schemes suggested by @jkittner & Team
- I removed the pills and vertical color legend on the line chart, excepted for UTCI+ and PET+ indicators
- This should now work as expected

PS: There are still some issues on the heat atlas page, which I will solve separately in #93 

LMKWYT

**Comment by alsino** [comment]
@vogelino 

One small detail: The UTCI color map currently only shows a "green" gradient, both in the legend and on the map. Was UTCI not supposed to use the turbo color scale (https://github.com/vogelino/data-2-resilience/issues/82#issue-2993695180) or is this the actual truncated scale? Maybe I am still missing something here?

<img width="966" alt="Image" src="https://github.com/user-attachments/assets/84db3816-2791-4888-8b3e-28b06e7ad1b5" />

**Comment by vogelino** [comment]
> Was UTCI not supposed to use the turbo color scale

@alsino It si the trucated part indeed. We only show the colors related to the respective category

**Comment by alsino** [comment]
@vogelino Amazing! Thanks for the quick clarification!

Closing this!

**Comment by jkittner** [comment]
Looks good! a few minor nit-picks:

![Image](https://github.com/user-attachments/assets/c05621cc-37df-4c01-b0f0-9531a339ad63)

The colorbar overlaps the x-axis labels. Maybe we could increase the padding and make it a tiny bit wider like this?

- The lightning strike distance is supposed to be in kilometers, not meters
- the wind direction has no colormap? iirc that already worked at some point? A cyclic colormap with a fixed range from 0 - 360?
